version: '3.8'
services:
  app:
    build:
      dockerfile: docker/php/Dockerfile
      context: .
      args:
        - APP_ENV=dev
    depends_on:
      - database
    environment:
      - APP_ENV=dev
    volumes:
      - ./:/php:cached
      - var:/php/var
    networks:
      - rsf-network

  nginx:
    image: nginx:1.23-alpine
    working_dir: /php
    volumes:
      - ./public:/php/public:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    ports:
      - "80:80"
    networks:
      - rsf-network

  database:
    image: mysql:8.0-oracle
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    command:
      --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    ports:
      - "3306:3306"
    volumes:
      - database_data:/var/lib/mysql
    networks:
      - rsf-network

volumes:
  var:
    external: true
  phpunit:
    external: true
  database_data:
    external: true

networks:
  rsf-network:
    driver: bridge
