{{- $fullname := (include "microservice-base.fullname" .) -}}
{{- $labels := (include "microservice-base.labels" .) -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullname }}-nginx
  namespace: {{ .Release.Namespace }}
  labels: {{- $labels | nindent 4 }}
    component: nginx
    {{- if .Values.podLabels }}
    {{- include "microservice-base.tplValue" (dict "value" .Values.podLabels "context" $) | nindent 8 }}
    {{- end }}
  annotations:
    checksum/values: {{ toYaml .Values | sha256sum | trunc 20 | quote }}
data:
  nginx.conf: |
    events {
      worker_connections  1024;
      multi_accept on;
    }
    http {

      keepalive_timeout 2 2;
      client_body_timeout 15;
      client_header_timeout 15;
      send_timeout 15;

      client_body_buffer_size 164;
      client_header_buffer_size 4k;
      client_max_body_size 10m;
      large_client_header_buffers 4 16k;

      open_file_cache max=2000 inactive=20s;
      open_file_cache_valid 60s;
      open_file_cache_min_uses 5;
      open_file_cache_errors off;

      server {
        listen 80 default_server;
        listen [::]:80 default_server;

        # Set nginx to serve files from the shared volume!
        root {{ .Values.nginx.docRoot }};
        server_name _;

        gzip on;
        gzip_min_length 1000;
        gzip_http_version 1.1;
        gzip_vary on;
        gzip_comp_level 6;
        gzip_buffers 32 4k;
        gzip_proxied any;
        gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript application/javascript text/x-js;

        location / {
          try_files $uri /index.php$is_args$args;
        }

        location ~ ^/index\.php(/|$) {
          include fastcgi_params;
          fastcgi_param REQUEST_METHOD $request_method;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_pass 127.0.0.1:9000;
          fastcgi_read_timeout 300;
          fastcgi_send_timeout 300;
        }
        location ~ \.php$ {
            return 404;
        }
      }
    }
