apiVersion: v1
kind: Service
metadata:
  name: {{ include "microservice-base.fullname" . }}-nginx
  labels:
    {{- include "microservice-base.labels" . | nindent 4 }}
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
    - port: {{ .Values.nginx.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "microservice-base.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
